=== OumaymaB/DTD/ex2.dtd
<!ELEMENT client (commande)+ >
<!ATTLIST client id ID #REQUIRED>
<!ELEMENT commande (ligneCommande)+ >
<!ATTLIST commande date CDATA #REQUIRED>
<!ELEMENT ligneCommande (produit, quantite) >
<!ELEMENT quantite (#PCDATA) >
<!ELEMENT produit (designation,prix) >
<!ELEMENT designation (#PCDATA) >
<!ELEMENT prix (#PCDATA) >

=== OumaymaB/DTD/ex2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE client SYSTEM "ex2.dtd">
<client id="">
    <commande date="">
        <ligneCommande>
            <produit>
                <designation></designation>
                <prix></prix>
            </produit>
            <quantite></quantite>
        </ligneCommande>
    </commande>
    
    <commande date="">
        <ligneCommande>
            <produit>
                <designation></designation>
                <prix></prix>
            </produit>
            <quantite></quantite>
        </ligneCommande>
    </commande>
</client>
